
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package filemanager;

/** CUP generated class containing symbol constants. */
public class symResponse {
  /* terminals */
  public static final int DUNO = 22;
  public static final int CLOSE_BRACKET = 13;
  public static final int GREATAPERTURE = 17;
  public static final int GREATCLOSE = 18;
  public static final int APERTURE = 15;
  public static final int OPEN_CURLY = 10;
  public static final int FILE = 21;
  public static final int END = 16;
  public static final int ERROR = 2;
  public static final int GREATER = 8;
  public static final int WARNING = 4;
  public static final int COL = 6;
  public static final int COLON = 9;
  public static final int ROW = 5;
  public static final int OPEN_BRACKET = 12;
  public static final int COMA = 14;
  public static final int EOF = 0;
  public static final int BLOCK_PARAMETER = 19;
  public static final int error = 1;
  public static final int CLOSE_CURLY = 11;
  public static final int TEXT = 20;
  public static final int OUT = 3;
  public static final int LESS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "OUT",
  "WARNING",
  "ROW",
  "COL",
  "LESS",
  "GREATER",
  "COLON",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "COMA",
  "APERTURE",
  "END",
  "GREATAPERTURE",
  "GREATCLOSE",
  "BLOCK_PARAMETER",
  "TEXT",
  "FILE",
  "DUNO"
  };
}

