
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.sqform;

/** CUP generated class containing symbol constants. */
public class symSq {
  /* terminals */
  public static final int DUNO = 31;
  public static final int WHERE = 30;
  public static final int CLOSE_BRACKET = 9;
  public static final int AND = 24;
  public static final int GREATCLOSE = 28;
  public static final int SELECT = 17;
  public static final int OR = 25;
  public static final int EQUAL = 29;
  public static final int APERTURE = 4;
  public static final int OPEN_CURLY = 6;
  public static final int SPECIFICATION = 20;
  public static final int NOT = 26;
  public static final int END = 12;
  public static final int GREATEAPERTURE = 27;
  public static final int GREATER = 3;
  public static final int CONSULT = 15;
  public static final int LESSER_THAN = 22;
  public static final int MORE_THAN = 21;
  public static final int COLON = 5;
  public static final int OPEN_BRACKET = 8;
  public static final int DIFFERENCE = 23;
  public static final int COMA = 11;
  public static final int INQUIRIES = 14;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int CLOSE_CURLY = 7;
  public static final int TEXT = 18;
  public static final int CONSULTDATA = 13;
  public static final int TO = 16;
  public static final int QUOTE_D = 10;
  public static final int LESS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LESS",
  "GREATER",
  "APERTURE",
  "COLON",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "QUOTE_D",
  "COMA",
  "END",
  "CONSULTDATA",
  "INQUIRIES",
  "CONSULT",
  "TO",
  "SELECT",
  "TEXT",
  "NUMBER",
  "SPECIFICATION",
  "MORE_THAN",
  "LESSER_THAN",
  "DIFFERENCE",
  "AND",
  "OR",
  "NOT",
  "GREATEAPERTURE",
  "GREATCLOSE",
  "EQUAL",
  "WHERE",
  "DUNO"
  };
}

