
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.indigo;

/** CUP generated class containing symbol constants. */
public class symIndigo {
  /* terminals */
  public static final int FORM = 29;
  public static final int MODIFY_F = 19;
  public static final int MODIFY_C = 26;
  public static final int NEW_USER = 11;
  public static final int CHECKBOX = 34;
  public static final int C_PARAMETERS = 27;
  public static final int NEW_F = 17;
  public static final int GREATER = 51;
  public static final int IMAGE = 37;
  public static final int POSALIGNMENT = 48;
  public static final int LESS = 50;
  public static final int ROWS = 42;
  public static final int DATE = 9;
  public static final int NEW_PASSWORD = 12;
  public static final int TEXTID = 61;
  public static final int NAME_F = 23;
  public static final int BOOL = 47;
  public static final int REQUIRED = 40;
  public static final int CLASS = 30;
  public static final int NAME_C = 28;
  public static final int ALIGNMENT = 58;
  public static final int OPEN_CURLY = 53;
  public static final int DELETE_U = 15;
  public static final int TEXTWIS = 46;
  public static final int ID = 21;
  public static final int FORM_PARAMETERS = 20;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int ADD_C = 24;
  public static final int LOGIN_U = 16;
  public static final int DELETE_F = 18;
  public static final int CLOSE_BRACKET = 56;
  public static final int URL = 44;
  public static final int START = 2;
  public static final int APERTURE = 4;
  public static final int TITTLE = 57;
  public static final int OPEN_BRACKET = 55;
  public static final int TEXTWS = 45;
  public static final int DELETE_C = 25;
  public static final int PAST_USER = 10;
  public static final int PASSWORD = 8;
  public static final int TOPIC = 22;
  public static final int COLS = 43;
  public static final int CREDENTIAL = 6;
  public static final int COLON = 52;
  public static final int CLOSE_CURLY = 54;
  public static final int INDEX = 59;
  public static final int TEXT_AREA = 33;
  public static final int FILE = 36;
  public static final int TEXT_CAMP = 32;
  public static final int FINAL = 3;
  public static final int DUNO = 60;
  public static final int COMBO = 38;
  public static final int TEXTV = 31;
  public static final int END = 5;
  public static final int RATIO = 35;
  public static final int CREATE_U = 13;
  public static final int MODIFY_U = 14;
  public static final int USER = 7;
  public static final int BUTTON = 39;
  public static final int OPTIONS = 41;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "START",
  "FINAL",
  "APERTURE",
  "END",
  "CREDENTIAL",
  "USER",
  "PASSWORD",
  "DATE",
  "PAST_USER",
  "NEW_USER",
  "NEW_PASSWORD",
  "CREATE_U",
  "MODIFY_U",
  "DELETE_U",
  "LOGIN_U",
  "NEW_F",
  "DELETE_F",
  "MODIFY_F",
  "FORM_PARAMETERS",
  "ID",
  "TOPIC",
  "NAME_F",
  "ADD_C",
  "DELETE_C",
  "MODIFY_C",
  "C_PARAMETERS",
  "NAME_C",
  "FORM",
  "CLASS",
  "TEXTV",
  "TEXT_CAMP",
  "TEXT_AREA",
  "CHECKBOX",
  "RATIO",
  "FILE",
  "IMAGE",
  "COMBO",
  "BUTTON",
  "REQUIRED",
  "OPTIONS",
  "ROWS",
  "COLS",
  "URL",
  "TEXTWS",
  "TEXTWIS",
  "BOOL",
  "POSALIGNMENT",
  "COMA",
  "LESS",
  "GREATER",
  "COLON",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "TITTLE",
  "ALIGNMENT",
  "INDEX",
  "DUNO",
  "TEXTID"
  };
}

