
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.formsafe;

/** CUP generated class containing symbol constants. */
public class symSqForm {
  /* terminals */
  public static final int FORM = 3;
  public static final int NEWFORM = 27;
  public static final int DBFORM = 26;
  public static final int ID_COMPONENT = 33;
  public static final int IDFORM = 28;
  public static final int VISIBILITY = 44;
  public static final int CHECKBOX = 9;
  public static final int TEXT_NOSPACES = 35;
  public static final int PRIVATE = 46;
  public static final int IMAGE = 12;
  public static final int POSALIGNMENT = 37;
  public static final int DATE = 42;
  public static final int ROWS = 17;
  public static final int DATA = 38;
  public static final int BOOL = 36;
  public static final int REQUIRED = 15;
  public static final int NAME_C = 2;
  public static final int FORMTITTLE = 29;
  public static final int ALIGNMENT = 6;
  public static final int OPEN_CURLY = 20;
  public static final int EOF = 0;
  public static final int TEXT_WITHSPACES = 34;
  public static final int error = 1;
  public static final int COMA = 25;
  public static final int URL = 19;
  public static final int PASSWORD = 41;
  public static final int NAME = 47;
  public static final int TOPIC = 30;
  public static final int OPEN_PARENTHESIS = 22;
  public static final int USER_CREATOR = 31;
  public static final int COLS = 18;
  public static final int COLON = 24;
  public static final int CLOSE_CURLY = 21;
  public static final int TEXT_AREA = 8;
  public static final int TEXT_CAMP = 7;
  public static final int FILE = 11;
  public static final int DUNO = 43;
  public static final int PUBLIC = 45;
  public static final int COMBO = 13;
  public static final int TEXTV = 5;
  public static final int RATIO = 10;
  public static final int CLOSE_PARENTHESIS = 23;
  public static final int USER = 40;
  public static final int DBUSER = 39;
  public static final int CLASSN = 4;
  public static final int STRUCT = 32;
  public static final int BUTTON = 14;
  public static final int OPTIONS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAME_C",
  "FORM",
  "CLASSN",
  "TEXTV",
  "ALIGNMENT",
  "TEXT_CAMP",
  "TEXT_AREA",
  "CHECKBOX",
  "RATIO",
  "FILE",
  "IMAGE",
  "COMBO",
  "BUTTON",
  "REQUIRED",
  "OPTIONS",
  "ROWS",
  "COLS",
  "URL",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "COLON",
  "COMA",
  "DBFORM",
  "NEWFORM",
  "IDFORM",
  "FORMTITTLE",
  "TOPIC",
  "USER_CREATOR",
  "STRUCT",
  "ID_COMPONENT",
  "TEXT_WITHSPACES",
  "TEXT_NOSPACES",
  "BOOL",
  "POSALIGNMENT",
  "DATA",
  "DBUSER",
  "USER",
  "PASSWORD",
  "DATE",
  "DUNO",
  "VISIBILITY",
  "PUBLIC",
  "PRIVATE",
  "NAME"
  };
}

